name: Build Tweak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          if [ ! -d "$HOME/theos" ]; then
            git clone --recursive https://github.com/theos/theos.git ~/theos
          fi
          if [ ! -d "$HOME/theos/sdks" ]; then
            git clone https://github.com/theos/sdks.git ~/theos/sdks
          fi
          echo "THEOS=/home/runner/theos" >> $GITHUB_ENV

      - name: Compile Tweak
        run: |
          export PATH=/home/runner/theos/bin:$PATH
          make

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdFixerPro-Dylib
          path: .theos/obj/AdFixerPro.dylib
