name: Build Tweak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git make clang curl

      - name: Setup Theos, Toolchain & SDKs
        run: |
          rm -rf ~/theos
          
          # تثبيت Theos كاملاً
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
          # تنظيف وسحب الـ SDKs
          rm -rf ~/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

          # تثبيت الـ Toolchain الرسمي للينكس الخاص بـ Theos (هذا هو الحل للخطأ 127)
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos-toolchain.sh)"

          echo "THEOS=/home/runner/theos" >> $GITHUB_ENV
          echo "/home/runner/theos/bin" >> $GITHUB_PATH

      - name: Compile Tweak
        run: |
          export PATH=/home/runner/theos/bin:$PATH
          make

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdFixerPro-Dylib
          path: .theos/obj/AdFixerPro.dylib
